#!/usr/bin/env bash


echo "This is the install script for development only"
echo "Report to README for other environment installation"

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DEV_DIR}/common.sh"

# Clone dependencies
for c in ${CALIOPEN_COMPONENTS}
do
    [[ -d "${CALIOPEN_DIR}/${c}" ]] || git clone ${BASE_URL}/caliopen.${c}.git "${CALIOPEN_DIR}/${c}"
done


# install packages
# TODO This should be removed as soon as the service is fully executed through fig.
# aptitude install python python-dev python-virtualenv libffi-dev


# create and activate venv
# TODO This should be removed as soon as the service is fully executed through fig.
[[ -d "${CALIOPEN_DIR}/venv" ]] || virtualenv ${VENV_OPTS} "${CALIOPEN_DIR}/venv"
source "${CALIOPEN_DIR}/venv/bin/activate"
# setup all deps in venv
for d in ${CALIOPEN_COMPONENTS}
do

  cd "${CALIOPEN_DIR}/${d}"
  if [ -f setup.py ] ; then
    python setup.py develop
  fi
  if [ -e requirements.txt ] ; then
    pip install -r requirements.txt
  fi

done

# Install docker-compose in virtualenv
[[ -z "$(which docker-compose)" ]] && pip install docker-compose


# Create data folders
cd "${CALIOPEN_DIR}"
[[ -d "${CALIOPEN_DIR}/.data/cassandra/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/cassandra/data"
[[ -d "${CALIOPEN_DIR}/.data/elasticsearch/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/elasticsearch/data"

# Install frontend
# ================
cd "${CALIOPEN_DIR}/frontend"
# Use docker-compose to launch npm if no local npm is found
command -v npm >/dev/null 2>&1 || supercharge_npm=1
if [[ ! -z "$supercharge_npm" ]]
then
    function node {
        docker-compose -f ${DEV_DIR}/fig.yml run node $@
    }
    function npm {
        docker-compose -f ${DEV_DIR}/fig.yml run npm $@
    }
    function ember {
        docker-compose -f ${DEV_DIR}/fig.yml run ember $@
    }
fi
source ./bin/install
declare ret="$?"
[[ "0" -eq "$ret" ]] || exit $ret

# And we're done
echo "DONE"
