#!/usr/bin/env bash
# Start Caliopen service for development purpose.
# Refer to README file for further information

source common.sh

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEB_DIR="${CALIOPEN_DIR}/web"
VENV_DIR="${CALIOPEN_DIR}/venv"

echo "Activate virtualenv"
source ${VENV_DIR}/bin/activate


echo "Start fig services in docker"
fig -f "${DEV_DIR}/fig.yml" up -d redis cassandra elasticsearch rabbitmq


echo "Start server"
pserve "${WEB_DIR}/development.ini.sample"
