#!/usr/bin/env bash
# Start Caliopen service for development purpose.
# Refer to README file for further information

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${DEV_DIR}/common.sh"

WEB_DIR="${CALIOPEN_DIR}/web"
VENV_DIR="${CALIOPEN_DIR}/venv"

echo "Activate virtualenv"
source "${CALIOPEN_DIR}/venv/bin/activate"

COMPOSE_CMD="docker-compose"

# Create data folders
cd "${CALIOPEN_DIR}"
[[ -d "${CALIOPEN_DIR}/.data/cassandra/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/cassandra/data"
[[ -d "${CALIOPEN_DIR}/.data/elasticsearch/data" ]] || mkdir -p "${CALIOPEN_DIR}/.data/elasticsearch/data"


echo "Start containers"
# A fixed Current Working Directory is required to ensure
# data directories are always the same.
cd "${DEV_DIR}"
$COMPOSE_CMD up -d redis cassandra elasticsearch rabbitmq


echo "Start server"
pserve --reload "${CALIOPEN_DIR}/web/development.ini.sample"

echo "stop containers"
$COMPOSE_CMD stop
